import React from 'react';
import { AnalysisResponse, AssumptionItem } from '../types';
import { X, Download, Printer, Shield, CheckCircle2, Code2, AlertTriangle, ListChecks } from 'lucide-react';

interface ReportModalProps {
  analysis: AnalysisResponse;
  originalText: string;
  onClose: () => void;
}

export const ReportModal: React.FC<ReportModalProps> = ({ analysis, originalText, onClose }) => {
  const currentDate = new Date().toISOString().split('T')[0];

  const confirmedCount = analysis.assumptions.filter(a => a.status === 'confirmed').length;
  const dismissedCount = analysis.assumptions.filter(a => a.status === 'dismissed').length;
  const unexaminedCount = analysis.assumptions.filter(a => a.status === 'unresolved' || a.status === 'unreviewed').length;

  const handleDownloadMarkdown = () => {
    let md = `# THE BLIND SPOT : DECISION EXAMINATION & VALIDATION BRIEF\n`;
    md += `**Date:** ${currentDate}\n`;
    md += `**Evaluation Standard:** Non-Directive Critical Thinking Companion\n`;
    md += `**Version:** 1.0 (Audit-Ready)\n\n`;
    md += `> **STATEMENT OF SCOPE & NON-RECOMMENDATION:**\n`;
    md += `> ${analysis.scope_disclaimer}\n\n`;
    md += `---\n\n`;

    md += `## 1. Executive Summary & Context\n`;
    md += `**Decision Narrative:** ${analysis.decision_summary}\n\n`;
    if (analysis.options_detected.length > 0) {
      md += `**Alternatives Under Evaluation:**\n`;
      analysis.options_detected.forEach((opt, i) => {
        md += `- Option ${i + 1}: ${opt}\n`;
      });
      md += `\n`;
    }

    if (analysis.confidence_before !== undefined) {
      md += `**Decision Confidence Record:**\n`;
      md += `- Confidence Before Analysis: **${analysis.confidence_before}%**\n`;
      if (analysis.confidence_after !== undefined) {
        md += `- Confidence After Deconstruction: **${analysis.confidence_after}%**\n`;
      }
      md += `*(Note: Changes in confidence are presented without algorithmic interpretation; epistemic humility is a natural outcome of examining blind spots.)*\n\n`;
    }

    md += `## 2. Assumption Register & Grounded Verification\n`;
    md += `| # | Assumption | Grounding Quote | Status | User Notes |\n`;
    md += `|---|---|---|---|---|\n`;
    analysis.assumptions.forEach((a, i) => {
      md += `| ${i + 1} | ${a.statement} | "${a.evidence_quote}" | ${a.status} | ${a.user_note || 'None'} |\n`;
    });
    md += `\n`;
    md += `**Triage Summary:** Confirmed: ${confirmedCount} | Rejected: ${dismissedCount} | Unexamined: ${unexaminedCount}\n\n`;

    md += `## 3. Overlooked Dimensions (Silent Gaps)\n`;
    analysis.overlooked_factors.forEach(f => {
      md += `### ${f.title} [${f.category}]\n`;
      md += `**Observed Absence:** ${f.observation}\n`;
      md += `**Significance:** ${f.relevance_why}\n\n`;
    });

    if (analysis.conflicts.length > 0) {
      md += `## 4. Reasoning Tensions & Cognitive Dissonance\n`;
      analysis.conflicts.forEach(c => {
        md += `- **Statement A:** "${c.statement_a}"\n`;
        md += `  **Statement B:** "${c.statement_b}"\n`;
        md += `  **Tension:** ${c.tension}\n\n`;
      });
    }

    if (analysis.pre_mortem_analysis && analysis.pre_mortem_analysis.length > 0) {
      md += `## 5. Prospective Hindsight (Pre-Mortem Failure Modes)\n`;
      analysis.pre_mortem_analysis.forEach(pm => {
        md += `### Plausible Failure Scenario\n`;
        md += `**Scenario:** ${pm.scenario}\n`;
        md += `**Root Assumption:** ${pm.tied_assumption}\n`;
        md += `**Diagnostic Inquiry:** ${pm.neutral_check}\n\n`;
      });
    }

    if (analysis.validation_plan && analysis.validation_plan.length > 0) {
      md += `## 6. Actionable Non-Prescriptive Validation Plan\n`;
      analysis.validation_plan.forEach((val, i) => {
        md += `${i + 1}. **${val.title}** (${val.target_dimension}): ${val.action_to_verify}\n`;
      });
      md += `\n`;
    }

    md += `## 7. Socratic Inquiries for Reflection\n`;
    analysis.socratic_questions.forEach((q, i) => {
      md += `${i + 1}. **${q.text}** *(Dimension: ${q.relates_to})*\n`;
    });

    md += `\n---\n`;
    md += `*Generated by The Blind Spot AI Thinking Companion. No algorithms decided your outcome.*`;

    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `assumption-report-${currentDate}.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadJSON = () => {
    const jsonStr = JSON.stringify(analysis, null, 2);
    const blob = new Blob([jsonStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `decision-session-${analysis.conversation_id}.json`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div
      style={{
        position: 'fixed',
        inset: 0,
        backgroundColor: 'rgba(24, 24, 24, 0.88)',
        backdropFilter: 'blur(8px)',
        zIndex: 1000,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '20px'
      }}
      className="no-print-overlay"
    >
      <div
        className="card print-container"
        style={{
          width: '100%',
          maxWidth: '920px',
          maxHeight: '92vh',
          display: 'flex',
          flexDirection: 'column',
          backgroundColor: 'var(--carbon)',
          border: '1px solid var(--grey-pewter)',
          boxShadow: '0 25px 50px rgba(0, 0, 0, 0.85)',
          overflow: 'hidden'
        }}
      >
        {/* Header Bar */}
        <div
          style={{
            padding: '16px 22px',
            borderBottom: '1px solid var(--border-default)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            backgroundColor: 'var(--slate-dark)'
          }}
          className="no-print"
        >
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
            <Shield size={18} color="var(--chalk)" />
            <h3 style={{ fontSize: '15px', color: 'var(--chalk)', margin: 0, fontWeight: 600 }}>
              Decision Brief & Epistemic Audit Report
            </h3>
          </div>
          <div style={{ display: 'flex', gap: '8px' }}>
            <button onClick={handleDownloadMarkdown} className="btn btn-secondary btn-sm" title="Export as Markdown text blob">
              <Download size={13} /> Markdown (.md)
            </button>
            <button onClick={handleDownloadJSON} className="btn btn-secondary btn-sm" title="Export session JSON">
              <Code2 size={13} /> JSON
            </button>
            <button onClick={handlePrint} className="btn btn-primary btn-sm" title="Print or save as PDF">
              <Printer size={13} /> Print / Save PDF
            </button>
            <button onClick={onClose} className="btn btn-ghost btn-sm" style={{ padding: '4px' }}>
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Printable Document Body */}
        <div
          style={{
            padding: '26px 34px',
            overflowY: 'auto',
            fontSize: '13px',
            lineHeight: 1.6,
            color: 'var(--platinum-soft)'
          }}
        >
          {/* Header Banner */}
          <div style={{ borderBottom: '1px solid var(--border-default)', paddingBottom: '16px', marginBottom: '22px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
              <div>
                <h1 style={{ fontSize: '22px', fontWeight: 800, color: 'var(--chalk)', marginBottom: '4px', letterSpacing: '-0.02em' }}>
                  THE BLIND SPOT : DECISION BRIEF
                </h1>
                <div style={{ fontSize: '11px', color: 'var(--grey-neutral)', fontFamily: 'var(--font-mono)' }}>
                  Audit Date: {currentDate} • Standard: Verified Non-Directive AI • Session ID: {analysis.conversation_id}
                </div>
              </div>
              <span className="badge badge-gold" style={{ fontSize: '11px' }}>
                <CheckCircle2 size={12} /> Guardrail Certified (0% Verdicts)
              </span>
            </div>

            <div
              style={{
                marginTop: '12px',
                padding: '10px 14px',
                backgroundColor: 'var(--void)',
                borderRadius: 'var(--radius-sm)',
                borderLeft: '3px solid var(--grey-pewter)',
                fontSize: '12px',
                color: 'var(--chalk)'
              }}
            >
              <strong>Scope Notice: </strong> {analysis.scope_disclaimer}
            </div>
          </div>

          {/* Section 1: Executive Overview */}
          <div style={{ marginBottom: '22px' }}>
            <h4 style={{ fontSize: '12px', textTransform: 'uppercase', letterSpacing: '0.05em', color: 'var(--grey-neutral)', marginBottom: '8px', fontFamily: 'var(--font-mono)' }}>
              1. Executive Overview & Context
            </h4>
            <p style={{ color: 'var(--chalk)', fontSize: '14px', marginBottom: '10px' }}>
              {analysis.decision_summary}
            </p>
            {analysis.options_detected.length > 0 && (
              <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', marginBottom: '10px' }}>
                {analysis.options_detected.map((opt, i) => (
                  <span key={i} className="badge badge-neutral" style={{ textTransform: 'none', fontSize: '11px' }}>
                    Option {i + 1}: {opt}
                  </span>
                ))}
              </div>
            )}
            {analysis.confidence_before !== undefined && (
              <div style={{ fontSize: '12px', color: 'var(--platinum-soft)', backgroundColor: 'var(--void)', padding: '6px 12px', borderRadius: '4px', display: 'inline-flex', gap: '12px' }}>
                <span>Initial Stated Confidence: <strong>{analysis.confidence_before}%</strong></span>
                {analysis.confidence_after !== undefined && (
                  <span>Post-Analysis Confidence: <strong>{analysis.confidence_after}%</strong></span>
                )}
              </div>
            )}
          </div>

          {/* Section 2: Assumption Register Table */}
          <div style={{ marginBottom: '22px' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '8px' }}>
              <h4 style={{ fontSize: '12px', textTransform: 'uppercase', letterSpacing: '0.05em', color: 'var(--grey-neutral)', fontFamily: 'var(--font-mono)' }}>
                2. Assumption Register (Quote-Grounded)
              </h4>
              <div style={{ fontSize: '11px', color: 'var(--platinum-soft)' }}>
                Confirmed: <strong>{confirmedCount}</strong> | Rejected: <strong>{dismissedCount}</strong> | Unexamined: <strong>{unexaminedCount}</strong>
              </div>
            </div>

            <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left', fontSize: '12px', border: '1px solid var(--border-default)' }}>
              <thead>
                <tr style={{ backgroundColor: 'var(--slate-dark)', color: 'var(--chalk)' }}>
                  <th style={{ padding: '8px 10px', borderBottom: '1px solid var(--border-default)', width: '35%' }}>Assumption</th>
                  <th style={{ padding: '8px 10px', borderBottom: '1px solid var(--border-default)', width: '25%' }}>Evidence Quote</th>
                  <th style={{ padding: '8px 10px', borderBottom: '1px solid var(--border-default)', width: '18%' }}>Verification</th>
                  <th style={{ padding: '8px 10px', borderBottom: '1px solid var(--border-default)', width: '22%' }}>Notes</th>
                </tr>
              </thead>
              <tbody>
                {analysis.assumptions.map((a, idx) => (
                  <tr key={idx} style={{ borderBottom: '1px solid var(--border-subtle)', backgroundColor: idx % 2 === 0 ? 'transparent' : 'rgba(255,255,255,0.02)' }}>
                    <td style={{ padding: '8px 10px', color: 'var(--chalk)' }}>{a.statement}</td>
                    <td style={{ padding: '8px 10px', fontFamily: 'var(--font-mono)', color: 'var(--platinum-mid)', fontSize: '11px' }}>
                      "{a.evidence_quote}"
                    </td>
                    <td style={{ padding: '8px 10px' }}>
                      <span className="badge badge-neutral" style={{ fontSize: '10px' }}>{a.status}</span>
                    </td>
                    <td style={{ padding: '8px 10px', color: 'var(--platinum-soft)', fontStyle: a.user_note ? 'italic' : 'normal' }}>
                      {a.user_note || '—'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Section 3: Overlooked Dimensions */}
          <div style={{ marginBottom: '22px' }}>
            <h4 style={{ fontSize: '12px', textTransform: 'uppercase', letterSpacing: '0.05em', color: 'var(--grey-neutral)', marginBottom: '8px', fontFamily: 'var(--font-mono)' }}>
              3. Overlooked Dimensions (Silent Gaps)
            </h4>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr', gap: '8px' }}>
              {analysis.overlooked_factors.map((f, i) => (
                <div key={i} style={{ backgroundColor: 'var(--void)', padding: '10px 12px', borderRadius: '4px', border: '1px solid var(--border-default)' }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '4px' }}>
                    <strong style={{ color: 'var(--chalk)', fontSize: '13px' }}>{f.title}</strong>
                    <span className="badge badge-neutral" style={{ fontSize: '10px' }}>{f.category}</span>
                  </div>
                  <p style={{ color: 'var(--platinum-soft)', fontSize: '12px', marginBottom: '4px' }}>
                    {f.observation}
                  </p>
                  <div style={{ fontSize: '11px', color: 'var(--grey-neutral)' }}>
                    <em>Why it matters: {f.relevance_why}</em>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Section 4: Reasoning Conflicts */}
          {analysis.conflicts.length > 0 && (
            <div style={{ marginBottom: '22px' }}>
              <h4 style={{ fontSize: '12px', textTransform: 'uppercase', letterSpacing: '0.05em', color: 'var(--grey-neutral)', marginBottom: '8px', fontFamily: 'var(--font-mono)' }}>
                4. Reasoning Tensions & Cognitive Dissonance
              </h4>
              {analysis.conflicts.map((c, i) => (
                <div key={i} style={{ backgroundColor: 'var(--void)', padding: '10px 12px', borderRadius: '4px', border: '1px solid var(--border-default)', marginBottom: '8px' }}>
                  <div style={{ display: 'flex', gap: '10px', fontSize: '12px', marginBottom: '6px' }}>
                    <div style={{ flex: 1, color: 'var(--chalk)', fontStyle: 'italic' }}>Quote A: "{c.statement_a}"</div>
                    <div style={{ flex: 1, color: 'var(--chalk)', fontStyle: 'italic' }}>Quote B: "{c.statement_b}"</div>
                  </div>
                  <div style={{ fontSize: '12px', color: 'var(--platinum-soft)' }}>
                    <strong>Tension:</strong> {c.tension}
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Section 5: Pre-Mortem Prospective Hindsight */}
          {analysis.pre_mortem_analysis && analysis.pre_mortem_analysis.length > 0 && (
            <div style={{ marginBottom: '22px' }}>
              <h4 style={{ fontSize: '12px', textTransform: 'uppercase', letterSpacing: '0.05em', color: 'var(--grey-neutral)', marginBottom: '8px', fontFamily: 'var(--font-mono)' }}>
                5. Prospective Hindsight (Pre-Mortem Failure Mechanisms)
              </h4>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
                {analysis.pre_mortem_analysis.map((pm, i) => (
                  <div key={i} style={{ backgroundColor: 'var(--void)', padding: '10px 12px', borderRadius: '4px', border: '1px solid var(--border-default)' }}>
                    <div style={{ color: 'var(--chalk)', fontSize: '12px', fontWeight: 600, marginBottom: '4px' }}>
                      Plausible Failure: {pm.scenario}
                    </div>
                    <div style={{ fontSize: '11px', color: 'var(--platinum-soft)', marginBottom: '4px' }}>
                      <strong>Root Assumption:</strong> {pm.tied_assumption}
                    </div>
                    <div style={{ fontSize: '11px', color: 'var(--grey-neutral)' }}>
                      <strong>Diagnostic Check:</strong> {pm.neutral_check}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Section 6: Validation Plan */}
          {analysis.validation_plan && analysis.validation_plan.length > 0 && (
            <div style={{ marginBottom: '22px' }}>
              <h4 style={{ fontSize: '12px', textTransform: 'uppercase', letterSpacing: '0.05em', color: 'var(--grey-neutral)', marginBottom: '8px', fontFamily: 'var(--font-mono)' }}>
                6. Actionable Non-Prescriptive Validation Plan
              </h4>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                {analysis.validation_plan.map((val, i) => (
                  <div key={i} style={{ backgroundColor: 'var(--void)', padding: '8px 12px', borderRadius: '4px', border: '1px solid var(--border-default)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <div>
                      <strong style={{ color: 'var(--chalk)', fontSize: '12px' }}>{val.title}: </strong>
                      <span style={{ color: 'var(--platinum-soft)', fontSize: '12px' }}>{val.action_to_verify}</span>
                    </div>
                    <span className="badge badge-neutral" style={{ fontSize: '10px' }}>{val.target_dimension}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Section 7: Socratic Questions */}
          <div style={{ marginBottom: '16px' }}>
            <h4 style={{ fontSize: '12px', textTransform: 'uppercase', letterSpacing: '0.05em', color: 'var(--grey-neutral)', marginBottom: '8px', fontFamily: 'var(--font-mono)' }}>
              7. Socratic Inquiries for Ongoing Reflection
            </h4>
            <ul style={{ paddingLeft: '18px', color: 'var(--chalk)', fontSize: '13px' }}>
              {analysis.socratic_questions.map((q, i) => (
                <li key={i} style={{ marginBottom: '6px' }}>
                  {q.text} <span style={{ color: 'var(--grey-neutral)', fontSize: '11px' }}>({q.relates_to})</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};
